### ISSUE TITLE
version0.5 crashed the game

### ISSUE THREAD

**Issue by FungJiHsu** [PonyWarrior/PonyQOL2#1]
[LogOutput.log](https://github.com/PonyWarrior/PonyQOL2/files/15446884/LogOutput.log)

0.4 is ok.

**Comment by PonyWarrior** [comment]
Let me guess, manual installation?

**Comment by FungJiHsu** [comment]
> Let me guess, manual installation?

Yes

**Comment by PonyWarrior** [comment]
That's your issue. Use R2Modman from the Hades II readme channel in the discord to install your mods.

**Comment by FungJiHsu** [comment]
> That's your issue. Use R2Modman from the Hades II readme channel in the discord to install your mods.

I tried this.
But it still crashed.
[LogOutput.log](https://github.com/PonyWarrior/PonyQOL2/files/15448214/LogOutput.log)

**Comment by PonyWarrior** [comment]
Delete everything you manually installed and use start modded in r2modman.

**Comment by FungJiHsu** [comment]
> Delete everything you manually installed and use start modded in r2modman.

🤣I would have thought you were talking about those mods which were downloaded on thunderstore.
Then I suddenly realized that I have downloaded ModUtil on Nexus.

DONE it!👌
